#include QMK_KEYBOARD_H
/* THIS FILE WAS GENERATED by preonic-layout-jeep.org */
enum custom_keycodes {
    KC_00 = SAFE_RANGE,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case KC_00:
        if (record->event.pressed) {
            SEND_STRING(SS_TAP(X_P0)SS_TAP(X_P0));
        } else {
        }
        break;
    }
    return true;
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = LAYOUT_ortho_5x12(
 KC_ESC  , KC_NLCK        , KC_PERC , KC_LPRN , KC_RPRN , KC_KP_SLASH   , KC_BSPC , KC_MUTE , KC_APP , KC_PSCR , KC_SLCK , KC_BRK  ,
 S(KC_E)    , S(KC_F)           , KC_P7    , KC_P8      , KC_P9      , KC_PAST       , KC_F10  , KC_F11  , KC_F12 , KC_INS  , KC_HOME , KC_PGUP ,
 S(KC_C)    , S(KC_D)           , KC_P4    , KC_P5      , KC_P6      , KC_PMNS       , KC_F7   , KC_F8   , KC_F9  , KC_DEL  , KC_END  , KC_PGDN ,
 S(KC_A)    , S(KC_B)           , KC_P1    , KC_P2      , KC_P3      , KC_PPLS       , KC_F4   , KC_F5   , KC_F6  , LCTL(KC_MINS) , KC_UP   , LCTL(KC_PLUS) ,
 KC_PENT , LALT_T(KC_SPC) , KC_P0    , KC_00     , KC_PDOT   , LT(1,KC_PENT) , KC_F1   , KC_F2   , KC_F3  , KC_LEFT , KC_DOWN , KC_RGHT) ,
[1] = LAYOUT_ortho_5x12(
KC_NO, KC_NO,KC_NO,KC_NO, KC_NO,KC_NO,KC_NO ,KC_NO    ,KC_NO  , KC_MSEL , KC_MPLY , KC_MSTP ,
KC_NO ,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO  , KC_F22 , KC_F23 , KC_F24 ,  KC_NO    ,KC_NO    , KC_MNXT ,
KC_NO ,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO  , KC_F19 , KC_F20 , KC_F21 ,  KC_NO    ,KC_NO    , KC_MPRV ,
KC_NO ,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO  , KC_F16 , KC_F17 , KC_F18 ,  KC_NO    , KC_VOLU ,KC_NO            ,
KC_NO ,KC_NO,KC_NO,KC_NO,KC_NO, KC_NO , KC_F13  ,KC_F14 , KC_F15 ,  KC_MRWD , KC_VOLD , KC_MFFD )
};
